# codecov.yml
# Codecov configuration for Rust project using llvm-cov

# Coverage configuration
coverage:
  # Precision for coverage percentages
  precision: 2
  
  # Round coverage percentages
  round: down
  
  # Coverage range (red to green)
  range: 50..80
  
  # Status checks configuration
  status:
    # Project coverage status
    project:
      default:
        # Target coverage percentage
        target: 80%
        # Threshold for coverage drop that will fail the status
        threshold: 2%
        # Only consider coverage on new lines
        only_pulls: false
    
    # Patch coverage status (only new code)
    patch:
      default:
        # Target coverage for new code
        target: 85%
        # Threshold for patch coverage
        threshold: 5%
        # Only run on pull requests
        only_pulls: true

# Comment configuration for PR
comment:
  # Layout configuration for PR comments
  layout: "reach, diff, flags, files"
  
  # Behavior settings
  behavior: default  # default, once, new, spammy
  
  # Require changes to post comment
  require_changes: true
  
  # Require base comparison
  require_base: false
  
  # Require head comparison  
  require_head: true
  
  # Custom comment template for Rust projects
  template: |
    ## 🦀 Rust Coverage Report
    
    **Overall Coverage**: {{ coverage }}% {{ coverage_trend }}
    **Coverage Diff**: {{ diff }}%
    
    {% if files %}
    ### 📁 Files Changed
    | File | Coverage | Diff |
    |------|----------|------|
    {% for file in files %}
    | `{{ file.name }}` | {{ file.coverage }}% | {{ file.diff }}% |
    {% endfor %}
    {% endif %}
    
    {% if flags %}
    ### 🚩 Coverage by Component
    {% for flag in flags %}
    - **{{ flag.name }}**: {{ flag.coverage }}%
    {% endfor %}
    {% endif %}
    
    ---
    *Generated by [Codecov](https://codecov.io) 🎯*

# Flags configuration for Rust components
flags:
  # Core library
  core:
    paths:
      - src/lib.rs
      - src/core/
    carryforward: true
  
  # Binary/CLI
  bin:
    paths:
      - src/main.rs
      - src/bin/
    carryforward: true
  
  # Unit tests
  unit:
    carryforward: true
    
  # Integration tests
  integration:
    paths:
      - tests/
    carryforward: true
  
  # Documentation tests
  doctest:
    carryforward: true

# GitHub configuration
github_checks:
  annotations: true

# Codecov bot configuration
codecov:
  # Require CI to pass before processing coverage
  require_ci_to_pass: true
  
  # Notify configuration
  notify:
    # Require coverage to succeed
    require_coverage: true
    
    # Wait for CI builds
    wait_for_ci: true

# Parsers configuration optimized for Rust/LLVM
parsers:
  # LLVM coverage format
  llvm:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  
  # Rust-specific settings
  rust:
    enable_partials: true
